apiVersion: v2
name: transcrobes
description: A Kubernetes Helm Chart for installing Transcrobes
version: 0.0.21
keywords:
  - Transcrobes
  - transcrob.es
sources:
  - https://gitlab.com/transcrobes/charts
home: https://transcrob.es
icon: https://transcrob.es/img/tc128.png
dependencies:
  - name: postgresql-ha
    version: 7.x.x
    alias: pgha
    repository: https://charts.bitnami.com/bitnami
    condition: pgha.enabled
    tags:
      - transcrobes-database

  - name: kafka
    version: 14.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
    tags:
      - transcrobes-kafka

  - name: common
    version: 1.x.x
    repository: https://charts.bitnami.com/bitnami
